apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: booking-db
spec:
  serviceName: "booking-db"
  replicas: {{ .Values.postgres.replicas }}
  selector:
    matchLabels:
      app: booking-db
  template:
    metadata:
      labels:
        app: booking-db
    spec:
      containers:
        - name: booking-db
          image: {{ .Values.image.postgres }}
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgres.user }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.password }}
            - name: POSTGRES_DB
              value: {{ .Values.postgres.db }}
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: booking-db-data
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "{{ .Values.postgres.user }}", "-d", "{{ .Values.postgres.db }}"]
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 1
            failureThreshold: 60
  volumeClaimTemplates:
    - metadata:
        name: booking-db-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.postgres.storage }}
